export const generalConstants: any = {
  SHOW_CAPITAL: "Show",
  SHOW_SIMPLE: "show",
  ENABLE: "enable",
  OUTPUTDOC_SHOW: "OutPutDoc:Show",
  SHOW_IN_DOCUMENT: "Show in Document",
  MIN_MAX: "minMax",
  CLE_Q: "CLE_Q",
  ADD_V: "ADD_V",
  VAL_Q: "VAL_Q",
  MAT_F: "MAT_F",
  QUESTION: "question",
  SECTION: "section",
  CHAPTER: "chapter",
  MAXIMUM: "MAXIMUM",
  MINIMUM: "MINIMUM",
  AND: "and",
  IF: "if",
  OR: "or",
  MINIMUM_LENGTH: "MINIMUM_LENGTH",
  MAXIMUM_LENGTH: "MAXIMUM_LENGTH",
  OBJECT: "object",
  SUCCESS: "success",
  SET_QUESTION_RESPONSE: "SET_QUESTION_RESPONSE",
  QUESTION_RESPONSE: "QUESTION_RESPONSE",
  ERROR: "error",
  EMP: "Emp",
  STRING: "string",
  ZERO: "0",
  DV: "dv",
  VR: "vr",
};
