export const generalConstants: any = {
  SHOW_CAPITAL: "Show",
  SHOW_SIMPLE: "show",
  OUTPUTDOC_SHOW: "OutPutDoc:Show",
  SHOW_IN_DOCUMENT: "Show in Document",
  MIN_MAX: "minMax",
  CLE_Q: "CLE_Q",
  ADD_V: "ADD_V",
  VAL_Q: "VAL_Q",
  MAT_F: "MAT_F",
  QUESTION: "question",
  SECTION: "section",
  CHAPTER: "chapter",
  MAXIMUM: "MAXIMUM",
  MINIMUM: "MINIMUM",
  MIN_MAX_VALIDATION:"minMaxValidation",
  MIN_CHECKBOX :"minCheckbox",
 MAX_CHECKBOX :"maxCheckbox",
  ZERO:"0",
  DISABLE :"disable",
  STRING : "string",
  MIN_VALUE:"minValue",
  MAX_VALUE : "maxValue",
  DATE_FORMAT:"YYYY-MM-DD",
  HEADER:"Header",
  LIST:"List",
  DATE:"Date",
  QQUESTION : "Question",
  SSTRING : "String",
  NUMERIC : "Numeric",
  QUE_TYPE:"questionType"
};
