export const languageConstantsForCountry : any = {
    en: {
        ExpressionBuilder_SaveButtonConstants: "Save",
        ExpressionBuilder_QuestionsLoadingConstants: "Questions Loading...!",
        ExpressionBuilder_AddButton: "Add",
        ExpressionBuilder_RemoveButton: "Delete",
        ExpressionBuilder_AddNestedButton: "Add Nested",
        ExpressionBuilder_ActionsLabelConstants: "Actions",
        ExpressionBuilder_MinMaxFieldStringConstants: "MinLength/MaxLength Field", 
        ExpressionBuilder_MinMaxFieldConstants: "Min/ Max Field",
        ExpressionBuilder_MinMaxLength: "Min Field",
        ExpressionBuilder_MinLengthStringConstants: "MinLength",
        ExpressionBuilder_MinLengthConstants: "Min",
        ExpressionBuilder_MaxLengthConstants: "Max",
        ExpressionBuilder_MaxLengthStringConstants: "MaxLength",
        ExpressionBuilder_AndorLabel: "And/Or",
        ExpressionBuilder_FieldLabel: "Field",
        ExpressionBuilder_OperatorLabel: "Operator",
        ExpressionBuilder_ValueLabel: "Value",
        ExpressionBuilder_ActionLbl: "Show",
        ExpressionBuilder_ShowInDoc: "Show in Document",
        ExpressionBuilder_AddQuesRef: "Add Question References",
        ExpressionBuilder_ClrQues: "Clear Question",
        ExpressionBuilder_AddValOrSetVal: "Add value or set value",
        ExpressionBuilder_ValFromAnotherQues: "Value from another question",
        ExpressionBuilder_MatheFormula: "Mathematical formula",
        ExpressionBuilder_SelectaQues: "Select a Question",
        ExpressionBuilder_AddValue: "Add Value",
        ExpressionBuilder_PleaseSlt: "Please select",
        ExpressionBuilder_ValidationRuleTab: "Validation Rule",
        ExpressionBuilder_DefaultValueTab: "Default Value",
        ExpressionBuilder_SelectaQuestion: "Select a Question",
        ExpressionBuilder_SelectaOperator	:"Select a Operator",
        ExpressionBuilder_PickaValueorQuestion: "Pick a Value or Question",
        ExpressionBuilder_PickaOperator: "Operator",
        ExpressionBuilder_SelectAValue: "Select a Value",
        ExpressionBuilder_AddValErrorMessage:	"Add value or set value required numbers.",
        ExpressionBuilder_DefaultValueErrorMessage:	"Please select an action in Default Value tab.",
        ExpressionBuilder_DefaultValueErrorMessageFieldEmpty:	"Fields cannot be empty in Default value tab.",
        ExpressionBuilder_ValidationRuleFieldEmpty:	"Fields cannot be empty in validarion rule tab.",
        ExpressionBuilder_DataSaved:	"Data Saved!",
        ExpressionBuilder_ValidationMustPassed:	"Validation Must be passed!",
        ExpressionBuilder_FristExpCannotChanged: "First Selected Expression cannot be changed.",
        ExpressionBuilder_SelectQuestions: "Select Questions",
        ExpressionBuilder_FieldsEmpty: "Fields cannot be empty",
        ExpressionBuilder_ErrorOccured: "Error Occured!",
        ExpressionBuilder_AtLeastOneActionNeedToSelect: "If the fields are not empty, you must select at least one action.",
        ExpressionBuilder_SameQuesRefForCurrentQuestion: "You cannot select the current question in a visibility rule."

    },
    po: {
        "saveButtonConstants": "Salvar",
        "questionsLoadingConstants": "Carregando Perguntas...!",
        "addButton": "+ Adicionar",
        "removeButton": "Excluir",
        "addNestedButton": "+ Adicionar Aninhado",
        "actionsLabelConstants": "Ações",
        "minMaxFieldStringConstants": "Campo Mínimo/Máximo",
        "minMaxFieldConstants": "Campo Mínimo/Máximo",
        "minMaxLength": "Campo Mínimo",
        "minLengthStringConstants": "Comprimento Mínimo:",
        "minLengthConstants": "Mínimo:",
        "maxLengthConstants": "Máximo:",
        "maxLengthStringConstants": "Comprimento Máximo:",
        "andorLabel": "E/Ou",
        "fieldLabel": "Campo",
        "operatorLabel": "Operador",
        "valueLabel": "Valor",
        "actionLbl": "Mostrar",
        "showInDoc": "Mostrar no Documento",
        "validationRuleTab": "MaValidation Rule",
        "defaultValueTab": "DdsDefault Value"
    },
    ge: {
        "saveButtonConstants": "Speichern",
        "questionsLoadingConstants": "Fragen werden geladen...!",
        "addButton": "+ Hinzufügen",
        "removeButton": "Löschen",
        "addNestedButton": "+ Verschachteln",
        "actionsLabelConstants": "Aktionen",
        "minMaxFieldStringConstants": "Mindestlänge/Höchstlänge Feld",
        "minMaxFieldConstants": "Min./Max. Feld",
        "minMaxLength": "Min. Feld",
        "minLengthStringConstants": "Mindestlänge",
        "minLengthConstants": "Min. Länge",
        "maxLengthConstants": "Max. Länge",
        "maxLengthStringConstants": "Höchstlänge",
        "andorLabel": "Und/Oder",
        "fieldLabel": "Feld",
        "operatorLabel": "Operator",
        "valueLabel": "Wert",
        "actionLbl": "Anzeigen",
        "showInDoc": "Im Dokument anzeigen"
    },
    fr:{
        "saveButtonConstants": "Enregistrer",
        "questionsLoadingConstants": "Chargement des questions...!",
        "addButton": "+ Ajouter",
        "removeButton": "Supprimer",
        "addNestedButton": "+ Ajouter imbriqué",
        "actionsLabelConstants": "Actions",
        "minMaxFieldStringConstants": "Champ Longueur Min./Max.",
        "minMaxFieldConstants": "Champ Min./Max.",
        "minMaxLength": "Champ Min.",
        "minLengthStringConstants": "Longueur Min.",
        "minLengthConstants": "Min.",
        "maxLengthConstants": "Max.",
        "maxLengthStringConstants": "Longueur Max. ",
        "andorLabel": "Et/Ou",
        "fieldLabel": "Champ",
        "operatorLabel": "Opérateur",
        "valueLabel": "Valeur",
        "actionLbl": "Afficher",
        "showInDoc": "Afficher dans le document"
    },
    sp: {
        "saveButtonConstants": "Guardar",
        "questionsLoadingConstants": "Cargando Preguntas...!",
        "addButton": "+ Agregar",
        "removeButton": "Eliminar",
        "addNestedButton": "+ Agregar Anidado",
        "actionsLabelConstants": "Acciones",
        "minMaxFieldStringConstants": "Campo Mínimo/Máximo",
        "minMaxFieldConstants": "Campo Mínimo/Máximo",
        "minMaxLength": "Campo Mínimo",
        "minLengthStringConstants": "Longitud Mínima",
        "minLengthConstants": "Mínimo",
        "maxLengthConstants": "Máximo",
        "maxLengthStringConstants": "Longitud Máxima",
        "andorLabel": "Y/O",
        "fieldLabel": "Campo",
        "operatorLabel": "Operador",
        "valueLabel": "Valor",
        "actionLbl": "Mostrar",
        "showInDoc": "Mostrar en el Documento"
    },
    du: {
        "saveButtonConstants": "Opslaan",
        "questionsLoadingConstants": "Vragen Laden...!",
        "addButton": "+ Toevoegen",
        "removeButton": "Verwijderen",
        "addNestedButton": "+ Voeg Genest Toe",
        "actionsLabelConstants": "Acties",
        "minMaxFieldStringConstants": "Minimale/L maximale Veldlengte",
        "minMaxFieldConstants": "Min./Max. Veld",
        "minMaxLength": "Min. Veld",
        "minLengthStringConstants": "Minimale lengte",
        "minLengthConstants": "Min. lengte",
        "maxLengthConstants": "Max. lengte",
        "maxLengthStringConstants": "Maximale lengte",
        "andorLabel": "En/Of",
        "fieldLabel": "Veld",
        "operatorLabel": "Operator",
        "valueLabel": "Waarde",
        "actionLbl": "Tonen",
        "showInDoc": "Tonen in Document"
    },
};