export const languageConstantsForCountry : any = {
    en: {
        saveButtonConstants: "Save",
        questionsLoadingConstants: "Questions Loading...!",
        addButton: "+ Add",
        removeButton: "Delete",
        addNestedButton: "+ Add Nested",
        actionsLabelConstants: "Actions",
        minMaxFieldStringConstants: "MinLength/MaxLength Field", 
        minMaxFieldConstants: "Min/ Max Field",
        minMaxLength: "Min Field",
        minLengthStringConstants: "MinLength:",
        minLengthConstants: "Min:",
        maxLengthConstants: "Min:",
        maxLengthStringConstants: "MaxLength:",
        andorLabel: "And/Or",
        fieldLabel: "Field",
        operatorLabel: "Operator",
        valueLabel: "Value"
    },
    ch: {
        saveButtonConstants: "爱耻爱耻",
        questionsLoadingConstants: "爱耻  爱耻...!",
        addButton: "+ 爱耻",
        removeButton: "爱耻爱耻",
        addNestedButton: "+ 爱耻 爱耻",
        actionsLabelConstants: "爱耻",
        minMaxFieldStringConstants: "爱耻/爱耻 爱耻", 
        minMaxFieldConstants: "爱耻/ 爱耻 爱耻",
        minMaxLength: "爱耻 爱耻",
        minLengthStringConstants: "爱耻:",
        minLengthConstants: "爱耻:",
        maxLengthConstants: "爱耻:",
        maxLengthStringConstants: "爱耻:",
        andorLabel: "爱耻/爱耻",
        fieldLabel: "爱耻",
        operatorLabel: "爱耻",
        valueLabel: "爱耻"
    },
    ru: {
        saveButtonConstants: "ежеви́ка",
        questionsLoadingConstants: "ежеви́ка  ежеви́ка...!",
        addButton: "+ ежеви́ка",
        removeButton: "ежеви́ка",
        addNestedButton: "+ ежеви́ка ежеви́ка",
        actionsLabelConstants: "ежеви́ка",
        minMaxFieldStringConstants: "ежеви́ка/ежеви ежеви́ка", 
        minMaxFieldConstants: "ежеви/ежеви ежеви́ка",
        minMaxLength: "ежеви́ка ежеви́ка",
        minLengthStringConstants: "ежеви́ка:",
        minLengthConstants: "ежеви́ка:",
        maxLengthConstants: "ежеви́ка:",
        maxLengthStringConstants: "ежеви́ка:",
        andorLabel: "ежеви́ка/ежеви́ка",
        fieldLabel: "ежеви́ка",
        operatorLabel: "ежеви́ка",
        valueLabel: "ежеви́ка"
    }
};