export const languageConstantsForCountry : any = {
    en: {
        saveButtonConstants: "Save",
        questionsLoadingConstants: "Questions Loading...!",
        addButton: "+ Add",
        removeButton: "Delete",
        addNestedButton: "+ Add Nested",
        actionsLabelConstants: "Actions",
        minMaxFieldStringConstants: "MinLength/MaxLength Field", 
        minMaxFieldConstants: "Min/ Max Field",
        minMaxLength: "Min Field",
        minLengthStringConstants: "MinLength:",
        minLengthConstants: "Min:",
        maxLengthConstants: "Min:",
        maxLengthStringConstants: "MaxLength:",
        andorLabel: "And/Or",
        fieldLabel: "Field",
        operatorLabel: "Operator",
        valueLabel: "Value",
        actionLbl: "Show",
        showInDoc: "Show in Document",

    },
    po: {
        "saveButtonConstants": "Salvar",
        "questionsLoadingConstants": "Carregando Perguntas...!",
        "addButton": "+ Adicionar",
        "removeButton": "Excluir",
        "addNestedButton": "+ Adicionar Aninhado",
        "actionsLabelConstants": "Ações",
        "minMaxFieldStringConstants": "Campo Mínimo/Máximo",
        "minMaxFieldConstants": "Campo Mínimo/Máximo",
        "minMaxLength": "Campo Mínimo",
        "minLengthStringConstants": "Comprimento Mínimo:",
        "minLengthConstants": "Mínimo:",
        "maxLengthConstants": "Máximo:",
        "maxLengthStringConstants": "Comprimento Máximo:",
        "andorLabel": "E/Ou",
        "fieldLabel": "Campo",
        "operatorLabel": "Operador",
        "valueLabel": "Valor",
        "actionLbl": "Mostrar",
        "showInDoc": "Mostrar no Documento"
    },
    ge: {
        "saveButtonConstants": "Speichern",
        "questionsLoadingConstants": "Fragen werden geladen...!",
        "addButton": "+ Hinzufügen",
        "removeButton": "Löschen",
        "addNestedButton": "+ Verschachteln",
        "actionsLabelConstants": "Aktionen",
        "minMaxFieldStringConstants": "Mindestlänge/Höchstlänge Feld",
        "minMaxFieldConstants": "Min./Max. Feld",
        "minMaxLength": "Min. Feld",
        "minLengthStringConstants": "Mindestlänge:",
        "minLengthConstants": "Min. Länge:",
        "maxLengthConstants": "Max. Länge:",
        "maxLengthStringConstants": "Höchstlänge:",
        "andorLabel": "Und/Oder",
        "fieldLabel": "Feld",
        "operatorLabel": "Operator",
        "valueLabel": "Wert",
        "actionLbl": "Anzeigen",
        "showInDoc": "Im Dokument anzeigen"
    },
    fr:{
        "saveButtonConstants": "Enregistrer",
        "questionsLoadingConstants": "Chargement des questions...!",
        "addButton": "+ Ajouter",
        "removeButton": "Supprimer",
        "addNestedButton": "+ Ajouter imbriqué",
        "actionsLabelConstants": "Actions",
        "minMaxFieldStringConstants": "Champ Longueur Min./Max.",
        "minMaxFieldConstants": "Champ Min./Max.",
        "minMaxLength": "Champ Min.",
        "minLengthStringConstants": "Longueur Min. :",
        "minLengthConstants": "Min. :",
        "maxLengthConstants": "Max. :",
        "maxLengthStringConstants": "Longueur Max. :",
        "andorLabel": "Et/Ou",
        "fieldLabel": "Champ",
        "operatorLabel": "Opérateur",
        "valueLabel": "Valeur",
        "actionLbl": "Afficher",
        "showInDoc": "Afficher dans le document"
    },
    sp: {
        "saveButtonConstants": "Guardar",
        "questionsLoadingConstants": "Cargando Preguntas...!",
        "addButton": "+ Agregar",
        "removeButton": "Eliminar",
        "addNestedButton": "+ Agregar Anidado",
        "actionsLabelConstants": "Acciones",
        "minMaxFieldStringConstants": "Campo Mínimo/Máximo",
        "minMaxFieldConstants": "Campo Mínimo/Máximo",
        "minMaxLength": "Campo Mínimo",
        "minLengthStringConstants": "Longitud Mínima:",
        "minLengthConstants": "Mínimo:",
        "maxLengthConstants": "Máximo:",
        "maxLengthStringConstants": "Longitud Máxima:",
        "andorLabel": "Y/O",
        "fieldLabel": "Campo",
        "operatorLabel": "Operador",
        "valueLabel": "Valor",
        "actionLbl": "Mostrar",
        "showInDoc": "Mostrar en el Documento"
    },
    du: {
        "saveButtonConstants": "Opslaan",
        "questionsLoadingConstants": "Vragen Laden...!",
        "addButton": "+ Toevoegen",
        "removeButton": "Verwijderen",
        "addNestedButton": "+ Voeg Genest Toe",
        "actionsLabelConstants": "Acties",
        "minMaxFieldStringConstants": "Minimale/L maximale Veldlengte",
        "minMaxFieldConstants": "Min./Max. Veld",
        "minMaxLength": "Min. Veld",
        "minLengthStringConstants": "Minimale lengte:",
        "minLengthConstants": "Min. lengte:",
        "maxLengthConstants": "Max. lengte:",
        "maxLengthStringConstants": "Maximale lengte:",
        "andorLabel": "En/Of",
        "fieldLabel": "Veld",
        "operatorLabel": "Operator",
        "valueLabel": "Waarde",
        "actionLbl": "Tonen",
        "showInDoc": "Tonen in Document"
    },
};